# runtime: python39

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
    operating_system: "ubuntu22"

service: recipes

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  GOOGLE_CLOUD_PROJECT: useful-matter-443602-f5

# env_variables:
#   admin: ''
#   name: ""
#   password: ""
#   msgCount: 0
#   test1: ""