runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  FLASK_ENV: 'production'

